apiVersion: v1
kind: Service
metadata:
  name: happy-service
spec:
  selector:
   app: happy
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sad-service
spec:
  selector:
    app: sad
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angry-service
spec:
  selector:
    app: angry
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
